<?= $this->doctype() ?>
<html class="no-js">
    <head>
        
        <?= $this->headMeta()?>
        <?= $this->headTitle()?>
        <?= $this->headLink()?>
        <?= $this->headScript()?>
        <?= $this->headStyle()?>
        

        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/css/main.css">

        <script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    </head>
    <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <?= $this->navigation()
          			->menu()
          			->setUlClass('nav navbar-nav')?>

        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <div class="container">
     <p>Vous êtes ici : <?= $this->navigation()->breadcrumbs()->setMinDepth(0)?></p>
     <?= $this->layout()->content ?>    
    </div> <!-- /container --> 
    
    <?php 
    	$this->inlineScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js');
    	$this->inlineScript()->appendFile('window.jQuery || document.write(\'<script src="/js/vendor/jquery-1.10.1.min.js"><\/script>');
    	$this->inlineScript()->appendFile('/js/vendor/bootstrap.min.js');
    	$this->inlineScript()->appendFile('/js/plugins.js');
    	$this->inlineScript()->appendFile('/js/main.js');
    ?>       
    
    </body>
</html>
